
# Player placeholder support: (playerName), (playerHealth), (playerVotesToday). for other player options please message me, so I can implement them
# There's also some server placeholders as well: (voteServices) <- returns the number of services enabled
# This group of messages has that support
# Please use MiniMessage for color and other formatting
claim-reminder: "<yellow>You found some treasure while you were away! Use <hover:show_text:'<green>Shift click to insert into chat'><insert:/spoils><gradient:#fff200:#ffa700>/spoils</gradient></insert></hover><yellow> to claim your treasure."
add-old-rewards: true # Stack old rewards to new ones, if set to false only the newest rewards will be shown
vote-services:
  - "Test1"
  - "Test2"
  - "Test3"
  - "Test4"
vote-incomplete-message: "<green>Thank you for voting (playerName)! Vote on all (voteServices) sites to receive a reward! [(playerVotesToday)/(voteServices)]"
vote-complete-message: "<gold>Thank you for voting on all (voteServices) sites (playerName)! your support is much appreciated."
instant-package-message: "Thanks for voting! Because you have the instant reward package you don't receive any extra rewords. Sorry!"