name: RejoinRewards
version: 1.0
main: me.cookie.rejoinrewards.RejoinRewards
description: A plugin that rewards players based on the time they were away.
api-version: 1.18
author: Cookie#8723

depend:
  - SemiCore

commands:
  jrewards:
    permission: jrewards.use
    description: Base command.
    usage: /jrewards

permissions:
  jrewards.use:
    description: Base command permission, without it you wont be able to use any subcommands.
    default: op
  jrewards.claim:
    description: Permission to allow the player to claim their rejoin rewards.
    default: op
  jrewards.view:
    description: Permission to allow the viewing of other player's rewards.
    default: op
  jrewards.clear:
    description: Permission to allow clearing of other player's rewards.
    default: op