name: Expeditions
version: 1.0
main: me.cookie.expeditions.Expeditions
description: A plugin that rewards players based on the time they were away.
api-version: 1.18
author: Cookie#8723
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.6.0'

depend:
  - CookieCore
  - Votifier

commands:
  spoils:
    permission: expeditions.spoils.claim
    description: Base spoils command.
    usage: /spoils
  etv:
    permission: expeditions.vote.test
    description: Opens a gui to test voting.
    usage: /evt
  testrewards:
    permission: expeditions.spoils.testrewards
    description: Test the possible rewards without being actually offline.
    usage: /testrewards <time|weight> <number>
  expeditions:
    permission: expeditions.admin
    description: Collection of admin commands to set/remove/etc rewards of players.
    usage: /expeditions <set|add|clear|view> <player> <weight|time> <number>

permissions:
  expeditions.spoils.claim:
    description: Permission to allow the player to claim their rejoin rewards.
    default: op
  expeditions.spoils.view:
    description: Permission to allow the viewing of other player's rewards.
    default: op
  expeditions.spoils.clear:
    description: Permission to allow clearing of other player's rewards.
    default: op
  expeditions.spoils.testrewards:
    description: Permission to allow testing possible rewards of time offline or weight.
    default: op
  expeditions.admin:
    description: Permission to allow usage of expedition admin commands.
    default: op