name: Expeditions
version: 1.0
main: me.cookie.expeditions.Expeditions
description: A plugin that rewards players based on the time they were away.
api-version: 1.18
author: Cookie#8723

depend:
  - CookieCore

commands:
  spoils:
    permission: expeditions.spoils.claim
    description: Base spoils command
    usage: /spoils

permissions:
  expeditions.spoils.claim:
    description: Permission to allow the player to claim their rejoin rewards.
    default: op
  expeditions.spoils.view:
    description: Permission to allow the viewing of other player's rewards.
    default: op
  expeditions.spoils.clear:
    description: Permission to allow clearing of other player's rewards.
    default: op